apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-react-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycicd
  template:
    metadata:
      labels:
        app: mycicd
    spec:
      containers:
        - name: mycicd 
          image: osygroup/my-react-app:latest  #using ${{ secrets.DOCKERHUB_USERNAME }} in place of 'osygroup' won't work (the deployment file doesn't inherit variables)
          ports:
          - containerPort: 80




---

apiVersion: v1
kind: Service
metadata:
    name: my-react-app
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: mycicd
