apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-react-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mycicd
  template:
    metadata:
      labels:
        app: mycicd
    spec:
      containers:
        - name: mycicd 
          image: ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest  #osygroup/my-react-app:latest
          ports:
          - containerPort: 80




---

apiVersion: v1
kind: Service
metadata:
    name: my-react-app
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: mycicd
