
name: "Deploy app to k8s cluster"
on:
  push:
    # run on pushes to master
    branches:
      - master
jobs:
  push-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
    - uses: azure/setup-kubectl@v1
    - name: kubectl deploy to cluster
      run: |
        kubectl apply -f ./deployment.yml -n boutique-app --kubeconfig mercyAKS
